#!/usr/bin/env bash
set -euo pipefail

# Creates per-site Linux user and WordPress Docker stack
# using networkr-companion templates.
#
# Example:
#   sudo pressilion-create-site \
#     --user user-site-123 \
#     --website-id 123 \
#     --domain example.com \
#     --letsencrypt-email admin@example.com \
#     --wp-admin-email admin@example.com

PRESSILION_USER="networkr"
NETWORKR_ROOT="/home/${PRESSILION_USER}/networkr-companion"
TEMPLATE_ROOT="${NETWORKR_ROOT}/Template"

GROUP_ADMIN="pressadmin"

log() {
  echo "[$(date +'%Y-%m-%d %H:%M:%S')] $*"
}

require_root() {
  if [[ "$(id -u)" -ne 0 ]]; then
    echo "This script must be run as root." >&2
    exit 1
  fi
}

usage() {
  cat <<EOF
Usage:
  pressilion-create-site --user USERNAME --website-id ID --domain DOMAIN \\
                         --letsencrypt-email EMAIL [--wp-admin-email EMAIL]

Required:
  --user                Linux username for the site (e.g. user-site-123)
  --website-id          Numeric website ID from Pressilion (used for DB port, etc.)
  --domain              Primary domain (e.g. example.com)
  --letsencrypt-email   Email for Let's Encrypt registration

Optional:
  --wp-admin-email      Email used for initial WP admin (default: same as LE email)

The script will:
  - Create / update the Linux user
  - Create /home/<user>/data/{backup,temp,db,site}
  - Copy template conf.d and data structure
  - Generate .env and docker-compose.yml
  - Bring up the Docker stack
EOF
}

########################################
# Arg parsing
########################################

SITE_USER=""
WEBSITE_ID=""
PRIMARY_DOMAIN=""
LETSENCRYPT_EMAIL=""
WP_ADMIN_EMAIL=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --user)
      SITE_USER="$2"; shift 2 ;;
    --website-id)
      WEBSITE_ID="$2"; shift 2 ;;
    --domain)
      PRIMARY_DOMAIN="$2"; shift 2 ;;
    --letsencrypt-email)
      LETSENCRYPT_EMAIL="$2"; shift 2 ;;
    --wp-admin-email)
      WP_ADMIN_EMAIL="$2"; shift 2 ;;
    -h|--help)
      usage; exit 0 ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1 ;;
  esac
done

if [[ -z "${SITE_USER}" || -z "${WEBSITE_ID}" || -z "${PRIMARY_DOMAIN}" || -z "${LETSENCRYPT_EMAIL}" ]]; then
  echo "Missing required arguments." >&2
  usage
  exit 1
fi

if [[ -z "${WP_ADMIN_EMAIL}" ]]; then
  WP_ADMIN_EMAIL="${LETSENCRYPT_EMAIL}"
fi

########################################
# Main
########################################

require_root

SITE_HOME="/home/${SITE_USER}"
SITE_ROOT="${SITE_HOME}"
DATA_DIR="${SITE_ROOT}/data"

log "Creating / ensuring Linux user '${SITE_USER}' exists..."

if ! id -u "${SITE_USER}" >/dev/null 2>&1; then
  useradd -m -s /bin/bash "${SITE_USER}"
  passwd -l "${SITE_USER}" || true
fi

# Ensure group for pressadmin exists and user home perms allow pressadmin
if ! getent group "${GROUP_ADMIN}" >/dev/null; then
  groupadd "${GROUP_ADMIN}"
fi

usermod -g "${SITE_USER}" "${SITE_USER}"  # primary group = itself
chown "${SITE_USER}:${GROUP_ADMIN}" "${SITE_HOME}"
chmod 750 "${SITE_HOME}"

log "Creating data directories under ${DATA_DIR}..."
mkdir -p "${DATA_DIR}/backup" "${DATA_DIR}/temp" "${DATA_DIR}/db" "${DATA_DIR}/site"
chown -R "${SITE_USER}:${GROUP_ADMIN}" "${DATA_DIR}"
chmod -R 770 "${DATA_DIR}"

# Copy template data structure (empty .gitkeep etc.)
if [[ -d "${TEMPLATE_ROOT}/data" ]]; then
  log "Syncing template data structure..."
  rsync -a "${TEMPLATE_ROOT}/data/" "${DATA_DIR}/"
  chown -R "${SITE_USER}:${GROUP_ADMIN}" "${DATA_DIR}"
fi

# Copy conf.d
log "Setting up conf.d/php.ini..."
mkdir -p "${SITE_ROOT}/conf.d"
cp -f "${TEMPLATE_ROOT}/conf.d/php.ini" "${SITE_ROOT}/conf.d/php.ini"
chown -R "${SITE_USER}:${GROUP_ADMIN}" "${SITE_ROOT}/conf.d"
chmod -R 770 "${SITE_ROOT}/conf.d"

########################################
# Generate .env from template
########################################

ENV_TEMPLATE="${TEMPLATE_ROOT}/.env.template"
ENV_TARGET="${SITE_ROOT}/.env"

if [[ ! -f "${ENV_TEMPLATE}" ]]; then
  echo "Env template not found at ${ENV_TEMPLATE}" >&2
  exit 1
fi

log "Generating .env for ${SITE_USER}..."

# Basic identity / naming
COMPOSE_PROJECT_NAME="${SITE_USER}"
PRIMARY_DOMAIN="${PRIMARY_DOMAIN}"
DOMAINS="${PRIMARY_DOMAIN}"

CONTAINER_DB_NAME="${COMPOSE_PROJECT_NAME}-db"
CONTAINER_SITE_NAME="${COMPOSE_PROJECT_NAME}-wp"
CONTAINER_CLI_NAME="${COMPOSE_PROJECT_NAME}-cli"

# DB names / credentials (you can swap this to values generated by Pressilion)
MYSQL_DATABASE="wp_${WEBSITE_ID}"
MYSQL_USER="wp_${WEBSITE_ID}_u"
MYSQL_PASSWORD="$(openssl rand -hex 16)"
MYSQL_ROOT_PASSWORD="$(openssl rand -hex 16)"

# DB local port (for SSH tunnelling). Adjust formula if needed.
DB_LOCAL_PORT=$((33060 + WEBSITE_ID))

# WP admin basics
WP_TITLE="${PRIMARY_DOMAIN}"
WP_ADMIN_USER="admin"
WP_ADMIN_TEMP_PASS="$(openssl rand -base64 18)"
WP_ADMIN_MAIL="${WP_ADMIN_EMAIL}"
WP_PERMA_STRUCTURE='/%year%/%monthnum%/%postname%/'

export WEBSITE_ID COMPOSE_PROJECT_NAME PRIMARY_DOMAIN DOMAINS \
       LETSENCRYPT_EMAIL CONTAINER_DB_NAME CONTAINER_SITE_NAME \
       CONTAINER_CLI_NAME MYSQL_DATABASE MYSQL_USER MYSQL_PASSWORD \
       MYSQL_ROOT_PASSWORD DB_LOCAL_PORT WP_TITLE WP_ADMIN_USER \
       WP_ADMIN_TEMP_PASS WP_ADMIN_MAIL WP_PERMA_STRUCTURE

# We need envsubst (gettext-base)
envsubst < "${ENV_TEMPLATE}" > "${ENV_TARGET}"

# Permissions so only pressilion/pressadmin can see .env
chown "${PRESSILION_USER}:${GROUP_ADMIN}" "${ENV_TARGET}"
chmod 640 "${ENV_TARGET}"

########################################
# docker-compose.yml
########################################

COMPOSE_TEMPLATE="${TEMPLATE_ROOT}/docker-compose.template.yml"
COMPOSE_TARGET="${SITE_ROOT}/docker-compose.yml"

if [[ ! -f "${COMPOSE_TEMPLATE}" ]]; then
  echo "docker-compose template not found at ${COMPOSE_TEMPLATE}" >&2
  exit 1
fi

log "Copying docker-compose template..."
cp -f "${COMPOSE_TEMPLATE}" "${COMPOSE_TARGET}"
chown "${PRESSILION_USER}:${GROUP_ADMIN}" "${COMPOSE_TARGET}"
chmod 640 "${COMPOSE_TARGET}"

########################################
# Start stack
########################################

log "Bringing up Docker stack for ${SITE_USER}..."
cd "${SITE_ROOT}"
docker compose up -d --build

########################################
# Summary
########################################

cat <<EOF

=====================================================
Site created successfully
=====================================================

Linux user:        ${SITE_USER}
Home:              ${SITE_HOME}
Data dir:          ${DATA_DIR}
Primary domain:    ${PRIMARY_DOMAIN}
LE email:          ${LETSENCRYPT_EMAIL}

DB Container:      ${CONTAINER_DB_NAME}
DB Name:           ${MYSQL_DATABASE}
DB User:           ${MYSQL_USER}
DB Password:       ${MYSQL_PASSWORD}
DB Root Password:  ${MYSQL_ROOT_PASSWORD}
DB Local Port:     ${DB_LOCAL_PORT}

WP Container:      ${CONTAINER_SITE_NAME}
WP CLI Container:  ${CONTAINER_CLI_NAME}
WP Title:          ${WP_TITLE}
WP Admin User:     ${WP_ADMIN_USER}
WP Admin Email:    ${WP_ADMIN_MAIL}
WP Temp Password:  ${WP_ADMIN_TEMP_PASS}

To access DB via SSH tunnel:

  ssh -L ${DB_LOCAL_PORT}:127.0.0.1:${DB_LOCAL_PORT} ${SITE_USER}@<server-ip>

Then connect your DB client to:

  Host: 127.0.0.1
  Port: ${DB_LOCAL_PORT}
  User: ${MYSQL_USER}
  Pass: ${MYSQL_PASSWORD}
  DB:   ${MYSQL_DATABASE}

EOF